<?php

namespace ContainerMuJboiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCreatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Creator\ArticleCreator' shared service.
     *
     * @return \App\Creator\ArticleCreator_AsyncProxy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Creator/ArticleCreatorInterface.php';
        include_once $container->targetDir.''.'/async_proxies/App_Creator_ArticleCreator_AsyncProxy.php';
        include_once \dirname(__DIR__, 4).'/src/Go/AsyncRunner.php';

        return $container->services['App\\Creator\\ArticleCreator'] = new \App\Creator\ArticleCreator_AsyncProxy(($container->privates['App\\Go\\AsyncRunner'] ??= new \App\Go\AsyncRunner($container)), ($container->services['App\\Creator\\ArticleCreator.inner'] ?? $container->load('getArticleCreator_InnerService')));
    }
}
