<?php

namespace ContainerMuJboiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoBoostCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GoBoostCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GoBoostCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('go:boost', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\GoBoostCommand')] fn (): \App\Command\GoBoostCommand => ($container->privates['App\\Command\\GoBoostCommand'] ?? $container->load('getGoBoostCommandService')));
    }
}
