<?php

namespace ContainerJ2NzHe5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NenVkKVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nenVkKV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nenVkKV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.hAbj0.E.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController::edit' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ArticleController::new()', 'getArticleControllernewService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.hAbj0.E.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController:edit' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::edit()', 'getArticleControllereditService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::delete()', 'getArticleControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::new' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::edit' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:new' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:edit' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
        ]);
    }
}
