<?php

namespace ContainerJ2NzHe5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCreator_InnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Creator\ArticleCreator.inner' shared autowired service.
     *
     * @return \App\Creator\ArticleCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Creator/ArticleCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Creator/ArticleCreator.php';

        return $container->services['App\\Creator\\ArticleCreator.inner'] = new \App\Creator\ArticleCreator(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
