<?php

namespace ContainerJ2NzHe5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateArticleCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateArticleCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateArticleCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-article', [], 'Creates an article asynchronously', false, #[\Closure(name: 'App\\Command\\CreateArticleCommand')] fn (): \App\Command\CreateArticleCommand => ($container->privates['App\\Command\\CreateArticleCommand'] ?? $container->load('getCreateArticleCommandService')));
    }
}
