<?php

namespace ContainerJ2NzHe5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoBoostCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GoBoostCommand' shared autowired service.
     *
     * @return \App\Command\GoBoostCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GoBoostCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Go/AsyncRunner.php';

        $container->privates['App\\Command\\GoBoostCommand'] = $instance = new \App\Command\GoBoostCommand(($container->privates['App\\Go\\AsyncRunner'] ??= new \App\Go\AsyncRunner($container)));

        $instance->setName('go:boost');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
