<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMuJboiH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMuJboiH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMuJboiH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMuJboiH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMuJboiH\App_KernelDevDebugContainer([
    'container.build_hash' => 'MuJboiH',
    'container.build_id' => 'f99f8713',
    'container.build_time' => 1761406089,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMuJboiH');
